# Generated by Django 3.0.7 on 2020-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0049_auto_20200720_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_domains',
            field=models.ManyToManyField(blank=True, to='status.ClientDomain', verbose_name='Client Domains'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='services',
            field=models.ManyToManyField(blank=True, to='status.Service', verbose_name='Service'),
        ),
    ]
