# Generated by Django 3.0.8 on 2020-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0050_auto_20200721_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='visual_order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
